/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproj;

import java.awt.Color;
import java.awt.Font;

import javax.swing.WindowConstants;

/**
 *
 *
 */
public class InfoForm extends javax.swing.JFrame
{
	
	/**
	 * 
	 */
	private static final long serialVersionUID = -8828447917216329654L;
	
	/**
	 * Creates new form InfoForm
	 */
	public InfoForm()
	{
		this.initComponents();
		this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
		Font font = new Font("Arial", Font.BOLD, 12);
		this.infoText.setBackground(Color.lightGray);
		this.infoText.setFont(font);
		this.infoText.setText("\nThis IDE was made as a final project at the\n"
				+ "software engeneering department at\n"
				+ "ORT Braude college, Karmiel, Israel\n\n"
				+ "Maria Gordover\n"
				+ "Max Igolinsky\n\n"
				+ "With the guidance of DR. Shtein Esti\n\n"
				+ "January 2014");
	}
	
	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents()
	{
		
		this.jLabel1 = new javax.swing.JLabel();
		this.CloseButton = new javax.swing.JButton();
		this.jScrollPane1 = new javax.swing.JScrollPane();
		this.infoText = new javax.swing.JTextArea();
		
		this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		this.setResizable(false);
		
		this.jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		this.jLabel1.setText("Pascal++ IDE");
		
		this.CloseButton.setText("Close");
		this.CloseButton.addActionListener(new java.awt.event.ActionListener()
		{
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				InfoForm.this.CloseButtonActionPerformed(evt);
			}
		});
		
		this.infoText.setColumns(20);
		this.infoText.setRows(5);
		this.jScrollPane1.setViewportView(this.infoText);
		
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this.getContentPane());
		this.getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
												.addGap(0, 0, Short.MAX_VALUE)
												.addComponent(this.CloseButton))
										.addGroup(layout.createSequentialGroup()
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(this.jLabel1)
														.addComponent(this.jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(0, 0, Short.MAX_VALUE)))
								.addContainerGap())
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(this.jLabel1)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(this.jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(this.CloseButton)
								.addContainerGap())
				);
		
		this.pack();
	}// </editor-fold>//GEN-END:initComponents
	
	private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt)
	{//GEN-FIRST:event_CloseButtonActionPerformed
		this.dispose();
	}//GEN-LAST:event_CloseButtonActionPerformed
	
	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[])
	{
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try
		{
			for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() )
			{
				if ("Nimbus".equals(info.getName()))
				{
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		}
		catch (ClassNotFoundException ex)
		{
			java.util.logging.Logger.getLogger(InfoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (InstantiationException ex)
		{
			java.util.logging.Logger.getLogger(InfoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (IllegalAccessException ex)
		{
			java.util.logging.Logger.getLogger(InfoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (javax.swing.UnsupportedLookAndFeelException ex)
		{
			java.util.logging.Logger.getLogger(InfoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		
		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			@Override
			public void run()
			{
				new InfoForm().setVisible(true);
			}
		});
	}
	
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton CloseButton;
	private javax.swing.JTextArea infoText;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JScrollPane jScrollPane1;
	// End of variables declaration//GEN-END:variables
}
